In [35]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Activation, Dropout
from tensorflow.keras.layers import Conv1D, MaxPool1D, GlobalMaxPooling1D
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [36]:
df = pd.read_csv("dataset-indonesia - Sheet1.csv")

df.head()

sentimen                                              Tweet
0         2  lagu bosan apa yang aku save ni huhuhuhuhuhuhu...
1         2  kita lanjutkan saja diam ini hingga kau dan ak...
2         1  doa rezeki tak putus inna haa zaa larizquna ma...
3         1  makasih loh ntar kita bagi hasil aku 99 9 sisa...
4         2  aku tak faham betul jenis orang malaysia yang ...

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10806 entries, 0 to 10805
Data columns (total 2 columns):
sentimen    10806 non-null int64
Tweet       10806 non-null object
dtypes: int64(1), object(1)
memory usage: 169.0+ KB


In [38]:
text = df["Tweet"].tolist()

print(text)

il BANDUNG ME LAWANN', "Wakakak right apakah skrng kita harus say goodbye dngn kokobop '", 'Nah luar negeri saja mau bantu bro apalagi kita semua anak bangsa ini momen kita mempererat persaudaraan Kita', 'Hug kita mumsssh', 'Maybe wkwk kita liat aja nnt', 'Kaya bocah abis dibeliin maenan baru ni sobatku', 'Mau nembak orang trs bilang saya tuh naksir naksir sebel sama kamu Ke siapa ya tapi wkwkwkwkwk', 'ke rumah dora', 'Dari kegagalan kita dapat membaca apa yang salah dari diri kita Berusaha dan berdoa hanya itulah kuncinya', 'Libra itu susah ditebak mereka bisa melakukan hal diluar dugaan kita', 'lanjutkan pa tirto', 'Orang kata indonesian suka minum susu ni Dia cuci badan Cuci dalam perut Mereka kata bang lepas ambil dadah', 'Mauliate dongan rina silalahi jerichosilalahi sudah support kita dengan belanja online asik ke kita Hotas PISO GA', 'Temen gue dikit kadang sampe gue ngerasa ga punya temen Kenapa Karena gue lebih nyaman sendiri Gue', 'Ah sudah lah Kita tunggu aja', 'Ayo dm yng b

In [39]:
print(len(text))

10806


In [40]:
y = df["sentimen"]
y = to_categorical(y)
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [41]:
df["sentimen"].value_counts()
#0 netral
#1 positif
#2 negatif

0    5327
2    2887
1    2592
Name: sentimen, dtype: int64

In [42]:
token = Tokenizer()
token.fit_on_texts(text)

In [43]:
token.index_word

{1: 'aku',
 2: 'kamu',
 3: 'yang',
 4: 'dan',
 5: 'kita',
 6: 'yg',
 7: 'di',
 8: 'ada',
 9: 'tak',
 10: 'ini',
 11: 'apa',
 12: 'orang',
 13: 'dia',
 14: 'ni',
 15: 'ya',
 16: 'itu',
 17: 'tapi',
 18: 'nak',
 19: 'mereka',
 20: 'ke',
 21: 'untuk',
 22: 'mau',
 23: 'kalau',
 24: 'juga',
 25: 'bisa',
 26: 'dari',
 27: 'dengan',
 28: 'jadi',
 29: 'lagi',
 30: 'kau',
 31: 'buat',
 32: 'sama',
 33: 'tu',
 34: 'aja',
 35: 'ga',
 36: 'akan',
 37: 'tidak',
 38: 'dah',
 39: 'jangan',
 40: 'kalo',
 41: 'gak',
 42: 'hari',
 43: 'bukan',
 44: 'dalam',
 45: 'je',
 46: 'boleh',
 47: 'semua',
 48: 'pernah',
 49: 'masih',
 50: 'suka',
 51: 'kan',
 52: 'karena',
 53: 'pun',
 54: 'baik',
 55: 'lebih',
 56: 'tau',
 57: 'allah',
 58: 'mana',
 59: 'saya',
 60: 'baru',
 61: 'bila',
 62: 'lah',
 63: 'adalah',
 64: 'banyak',
 65: 'lain',
 66: 'nanti',
 67: 'nya',
 68: 'la',
 69: 'dulu',
 70: 'harus',
 71: 'udah',
 72: 'hati',
 73: 'sudah',
 74: 'punya',
 75: 'jika',
 76: 'batik',
 77: 'pada',
 78: 'macam',
 

In [44]:
vocab = len(token.index_word) + 1
print(vocab)

22707


In [45]:
x = ["aku lagi galau nih"]
token.texts_to_sequences(x)

[[1, 29, 2699, 122]]

In [46]:
encode_text = token.texts_to_sequences(text)
# print(encode_text)

In [47]:
#normalization
max_kata = 100
X = pad_sequences(encode_text, maxlen=max_kata, padding="post")
print(X)

[[  434  1051    11 ...     0     0     0]
 [    5  4557   110 ...     0     0     0]
 [  291   538     9 ...     0     0     0]
 ...
 [  325     6   317 ...     0     0     0]
 [  126   222    21 ...     0     0     0]
 [  140    57 22706 ...     0     0     0]]


In [48]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=40, test_size=0.3, stratify=y)

In [128]:
X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
Y_train = np.asarray(Y_train)
Y_test = np.asarray(Y_test)

In [115]:
vec_size = 300
model = Sequential()
model.add(Embedding(vocab, vec_size, input_length=max_kata))
model.add(Conv1D(64, 8, activation="relu"))
model.add(MaxPool1D(2))
model.add(Dropout(0.5))

model.add(Dense(32, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(16, activation="relu"))
model.add(GlobalMaxPooling1D())
model.add(Dense(3, activation="softmax"))
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 100, 300)          6812100   
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 93, 64)            153664    
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, 46, 64)            0         
_________________________________________________________________
dropout_10 (Dropout)         (None, 46, 64)            0         
_________________________________________________________________
dense_15 (Dense)             (None, 46, 32)            2080      
_________________________________________________________________
dropout_11 (Dropout)         (None, 46, 32)            0         
_________________________________________________________________
dense_16 (Dense)             (None, 46, 16)          

In [116]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [117]:
model.fit(X_train, Y_train, epochs=2, validation_data=(X_test, Y_test))

Train on 7564 samples, validate on 3242 samples
Epoch 1/2
7564/7564 [==============================] - 58s 8ms/sample - loss: 1.0490 - acc: 0.4907 - val_loss: 1.0623 - val_acc: 0.4821
Epoch 2/2
7564/7564 [==============================] - 64s 8ms/sample - loss: 0.9981 - acc: 0.5140 - val_loss: 1.0170 - val_acc: 0.4904


In [133]:
def get_encode(x):
    x = token.texts_to_sequences(x)
    x = pad_sequences(x, maxlen=max_kata, padding="post")
    return x

In [134]:
x = ["saya sedang bingung pikiran"]
get_encode(x)

array([[  59,  268,  670, 3631,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0]], dtype=int32)

In [140]:
model.predict_classes(x)

AttributeError: 'str' object has no attribute 'shape'